version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: .
    command: bash -c "bin/rails db:create RAILS_ENV=production && bin/rails db:migrate RAILS_ENV=production && bundle exec rails s -b '0.0.0.0' -p 3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
