name: Deploy Rails App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.5

    - name: Build Docker image
      run: docker build -t myapp .

    - name: Push Docker image to DockerHub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker tag myapp:latest mydockerhubuser/myapp:latest
        docker push mydockerhubuser/myapp:latest

    - name: Deploy to AWS
      run: |
        terraform init
        terraform apply -auto-approve
